apiVersion: v1
kind: Service
metadata:
  name: minikube-test-api
spec:
  selector:
    app: minikube-api
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 32001 