apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-api
spec:
  selector:
    matchLabels:
      app: minikube-api
  replicas: 1
  template:
    metadata:
      labels:
        app: minikube-api
    spec:
      containers:
        - name: minikube-test-api-1
          image: asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DATABASE
              value: signupapp
            - name: POSTGRES_HOST 
              value: postgres-service
            - name: GUARD_PORT
              value: "4000"
