apiVersion: v1
kind: Service
metadata:
  name: minikube-test-client-service
spec:
  selector:
    app: minikube-client
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31001
      