---
kind: pipeline
type: ssh
name: ssrunner



server:
  host: 51.20.82.133
  user: ubuntu
  ssh_key:
    from_secret: SSH_PRIVATE_KEY

node:
  repo: ssh

steps:

  - name: configure gcloud
    image: docker.io/kameshsampath/drone-gcloud-auth
    pull: if-not-exists
    environment:
      dsecret:
        from_secret: dsecret_secret  
    commands:
      - echo "$dsecret" | base64 --decode > abc.json
      - gcloud auth activate-service-account --key-file=abc.json


  - name: build-docker-image1
    image: asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_api:latest
    commands:
     - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-south2-docker.pkg.dev
     - cd backend/auth
     - docker build -t docker-test_api:latest .
     - docker tag docker-test_api asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_api:latest
     - docker push asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_api:latest

  - name: build-docker-image2
    image: docker-test_client
    commands:
      - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-south2-docker.pkg.dev
      - cd web/
      - docker build -t docker-test_client:latest .
      - docker tag docker-test_client asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_client:latest
      - docker push asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_client:latest

  - name: helm-upgrade
    commands:
      - gcloud container clusters get-credentials test-cluster --region asia-south2 --project striking-figure-396805
      - helm upgrade release1 ./test1

trigger:
  branch:
    only:
      - main

