---
kind: pipeline
type: ssh
name: sshrunner



server:
  host: 16.171.239.132
  user: ubuntu
  ssh_key:
    from_secret: SSH_PRIVATE_KEY

node:
  repo: ssh

steps:

  - name: configure gcloud
    image: docker.io/kameshsampath/drone-gcloud-auth
    pull: if-not-exists
    settings:
      google_application_credentials:
        from_secret: service_account_json
      google_cloud_project:
        from_secret: google_cloud_project


  - name: build-docker-image1
    image: asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_api:latest
    commands:
     - cd backend/auth
     - docker build -t docker-test_api:latest .
     - docker tag docker-test_api asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_api:latest
     - gcloud auth activate-service-account --key-file=abc.json
     - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-south2-docker.pkg.dev
     - docker push asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_api:latest

  - name: build-docker-image2
    image: asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_client:latest
    commands:
      - cd web/
      - docker build -t docker-test_client:latest .
      - docker tag docker-test_client asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_client:latest
      - gcloud auth activate-service-account --key-file=abc.json
      - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-south2-docker.pkg.dev
      - docker push asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_client:latest

  - name: helm-upgrade
    commands:
      - gcloud auth activate-service-account --key-file=abc.json
      - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-south2-docker.pkg.dev
      - gcloud container clusters get-credentials test-cluster --region asia-south2 --project striking-figure-396805
      - helm upgrade release1 ./test1

trigger:
  branch:
    only:
      - main

