version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./backend/auth"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=signupapp
      - POSTGRES_HOST=postgresdb
      - GUARD_PORT=4000
    ports:
      - "4000:4000"
    links:
      - postgres:postgresdb


  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=signupapp
    ports:
      - "5432:5432"

  client:
    container_name: app-prod1
    build:
      context: "./web"
      target: production

      
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

    depends_on:
      - postgres