---
kind: pipeline
type: kubernetes
name: default

# Define your secrets
secrets:
  - name: kubeconfig
    source: dronesecret  # This should match the name of the secret in Drone

steps:
  - name: deploy-adminer
    image: adminer
    settings:
      kubeconfig:
        from_secret: kubeconfig
      namespace: default  # Change to your namespace
      commands:
        - apply -f adminer-service.yml
        - apply -f minikube-adminer.yml

  - name: deploy-api
    image: asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_api:latest
    settings:
      kubeconfig:
        from_secret: kubeconfig
      namespace: default  # Change to your namespace
      commands:
        - apply -f minikube-test-api.yml
        - apply -f minikube-test-api-service.yml

  - name: deploy-client
    image: asia-south2-docker.pkg.dev/striking-figure-396805/testgcpdep/docker-test_client:latest
    settings:
      kubeconfig:
        from_secret: kubeconfig
      namespace: default  # Change to your namespace
      commands:
        - apply -f minikube-client.yml
        - apply -f minikube-test-client-service.yml

  - name: deploy-postgres
    image: postgres
    settings:
      kubeconfig:
        from_secret: kubeconfig
      namespace: default  # Change to your namespace
      commands:
        - apply -f postgres-service.yml
        - apply -f postgres2.yml

# Define the `when` conditions to control when to trigger the pipeline
trigger:
  event:
    - push

