apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  selector:
    app: minikube-adminer
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000