apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: minikube-postgres
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31004